"""Copies the scoring code into the simulator so its Docker image is self-contained.

The simulator may not import from ml/ (root rule 2), so it carries a generated copy. Only the
import lines are rewritten; a test fails if the copy drifts from the originals.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
FEATURES = ROOT / "ml" / "src" / "features"
TARGET = ROOT / "simulator" / "src" / "vendor" / "linda"

SOURCES = {  # vendored name -> original
    "normalize.py": FEATURES / "normalize" / "normalize.py",
    "simhash.py": FEATURES / "fingerprint" / "simhash.py",
    "metadata.py": FEATURES / "scoring" / "metadata.py",
    "categories.py": FEATURES / "scoring" / "categories.py",
    "scorer.py": FEATURES / "scoring" / "scorer.py",
}
_REWRITES = [
    ("src.features.normalize.normalize", "src.vendor.linda.normalize"),
    ("src.features.fingerprint.simhash", "src.vendor.linda.simhash"),
    ("src.features.scoring.metadata", "src.vendor.linda.metadata"),
    ("src.features.scoring.categories", "src.vendor.linda.categories"),
    ("src.features.scoring.scorer", "src.vendor.linda.scorer"),
]
HEADER = "# GENERATED by ml/src/features/export/vendor.py from ml/src/features/. DO NOT EDIT: change the original and re-run `make export-model`.\n"


def vendored_sources() -> dict[str, str]:
    out = {"__init__.py": HEADER}
    for name, path in SOURCES.items():
        text = path.read_text(encoding="utf-8")
        for old, new in _REWRITES:
            text = text.replace(old, new)
        out[name] = HEADER + text
    return out


def write_vendor() -> None:
    TARGET.mkdir(parents=True, exist_ok=True)
    for parent in (TARGET.parent.parent, TARGET.parent):
        (parent / "__init__.py").touch()
    for name, text in vendored_sources().items():
        (TARGET / name).write_text(text, encoding="utf-8")
